core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:id>/', views.detail, name='detail'),
    path('add/<int:id>/', views.add, name='add'),
    path('remove/<int:id>/', views.remove, name='remove'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='login'),
]

shop/models.py
from itertools import product
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=255)
    feature_image = models.ImageField(upload_to='images/')
    description = models.TextField()
    price = models.DecimalField(decimal_places=3, max_digits=10000)

    def __str__(self):
        return self.name

class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name}'s image"

class Color(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.product.name}' color"

class Size(models.Model):
    product = models.ForeignKey(Product ,on_delete=models.CASCADE)
    size = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.product.name}' size"

class CartItem(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

class Cart(models.Model):
    user =models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(CartItem)
    ordered = models.BooleanField(default=False)
    #ordered_date = models.DateTimeField(timezone.now)

    def __str__(self):
        return self.user.username

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Install pillow to use PIL
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    #uploads all the profile picture images to 'profile_imgs' folder
    profile_img = models.ImageField(upload_to='profile_imgs', default='default/default.jpg')

    def __str__(self):
        return f"{self.user.username}'s profile"

    # before saving the image, gets the images and changes the size of the image
    #def save(self):
    #    super().save()
#
    #    img = Image.open(self.profile_img.path)
    #    if img.height > 300 or img.width > 300:
    #        output_size = (300,300)
    #        img.thumbnail(output_size)
    #        img.save(self.profile_img.path)

class Address(models.Model):
    address = models.ForeignKey( Profile, on_delete=models.SET_NULL, null=True)
    address_line_1 = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    country = models.CharField(max_length=150)


    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Address'

users/forms.py
from dataclasses import field
from django import forms
from django.forms import EmailField, ModelForm
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm, ModelForm ):
    #UserCreationForm doesn't come with and email so this line adds an email field to the form
    email = forms.EmailField(required=True)
    class Meta:
        model= User
        fields = ['username', 'email', 'password1','password2']

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Product, Cart, CartItem
from django.utils import timezone


def home(request):
    products = Product.objects.all()
    context = {
        'products':products,
    }
    return render(request, 'shop/home.html', context)

def detail(request, id):
    product = Product.objects.get(id=id)

    context = {
        'product':product,
    }

    return render(request, 'shop/detail.html', context)

def add(request, id):
    #Get the product to be added to the cart
    product = get_object_or_404(Product, id=id)
    #Get item if it's already in the cart_item or create a cart_item for the product
    cart_item, created = CartItem.objects.get_or_create(product=product, user=request.user, ordered=False)
    #Filter according to the current logged in user and incomplete oreders
    cart_ = Cart.objects.filter(user=request.user, ordered = False)
    #If there are any incomplete orders for the current logged in user:
    if cart_.exists():
        cart = cart_[0]
        if cart.products.filter(product__id=product.id).exists():
            cart_item.quantity += 1
            cart_item.save()
        else:
            cart.products.add(cart_item)
    else:
        #ordered_date = timezone.now()
        cart = Cart.objects.create(user=request.user)
        cart.products.add(cart_item)
    return redirect("home")

def remove(request, id):
    #Get the product to be added to the cart
    product = get_object_or_404(Product, id=id)
    cart_ = Cart.objects.filter(user=request.user, ordered = False)
    if cart_.exists():
        cart = cart_[0]
        if cart.products.filter(product__id=product.id).exists():
            cart_item = CartItem.objects.filter(product=product, user=request.user, ordered=False)[0]
            cart_item.product.remove(cart_item)
            return redirect('home')
        else:
            return redirect('home')
    else:
        return redirect('home')

    return redirect("home")

users/views.py
from email import message
from http.client import ImproperConnectionState
from django.shortcuts import render, redirect
from .models import Profile
from .forms import RegistrationForm
from django.core.mail import send_mail
from django.conf import settings

def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            recipient = form.cleaned_data.get('email')
            send_mail = ("Welcome To Winfred Ecommerce !", "We very delighted to have you.", "We very delighted to have you.", settings.EMAIL_HOST_USER, recipient)
            form.save()
            return redirect('login')
    else:
        form = RegistrationForm()

    return render(request, 'users/registration.html', {'form':form})

def profile(request):
    profile = Profile.objects.all()
    context={
        'profile':profile
    }
    return render(request,'users/profile.html', context)

templates/shop/add.html
{% if cart %}
{% for c in cart %}
    {{product.name}}
    {{product.price}}
{% endfor %}
{% endif %}

templates/shop/detail.html
{% extends './index.html' %}
{% load static %}
{% block content %}
    <div class='container'>
        <img class="img-responsive" src={{product.feature_image.url}} width='300px'>
        <h4>{{product.name}}</h4>
        <p>{{product.price}} </p> <a id="{{product.id}}" href='{% url 'add' product.id %}'>add to cart</a>
        <a id="{{product.id}}" href='{% url 'remove' product.id %}'>remove from cart</a>
        <p>{{product.description}}</p>
        {% for image in product.image_set.all %}
            <img class="img-responsive" src={{image.image.url}} width='100px'>
        {% endfor %}
        {% if product.color %}
        <h4>Available Colors</h4>
        {% endif %}
        {% for color in product.color_set.all %}
            <p>{{color.color}}</p>
        {% endfor %}
        {% if product.size %}
        <h4>Available Sizes</h4>
        {% endif %}
        {% for size in product.size_set.all %}
            <p>{{size.size}}</p>
        {% endfor %}
        {% if product.color == None %}
        <h4>No avialable colors</h4>
        {% endif %}
        {% if product.size == None %}
        <h4>No avialable Sizes</h4>
        {% endif %}
    </div>
{% endblock content %}

templates/shop/home.html
{% extends './index.html' %}
{% load static %}
<div class="row">
    {% block content %}
    {% for product in products %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{product.feature_image.url}}"  class="card-img-top">
                <div class="card-body">
                    <div class="card-title">{{product.title}}</div>
                    <div class="card-text">{{product.price}}</div>
                    <a href="{% url 'detail' product.id %}" class="btn btn-warning">View Item</a>
                    <button id="{{product.id}}" href="#" class="btn atc btn-warning">Add To Cart</button>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endblock content %}
    </div>
</div>

templates/shop/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/users/login.html
{% extends '../shop/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class='content-section'>
        <form method='POST'>
            {% csrf_token %}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Login Here</legend>
                {{form|crispy}}
            </fieldset>
            <div class='form-group'>
                <button class='btn btn-outline-info' type='submit'>Login</button>
                <small class='muted'> <a class='ml-2' href='#'>Forgotten password</a></small>
            </div>
        </form>
        <div class='border-top pt-3'>
            <small class='muted'>Don't have an account? <a class='ml-2' href='{% url 'registration' %}'>Sign Up</a></small>
        </div>
    </div>
{% endblock content %}

templates/users/logout.html
{% extends '../shop/index.html' %}
{% block content %}
    <h2>You have been Logged Out</h2>
    <div class='border-top pt-3'>
        <small class='muted'><a href='{% url 'login' %}'>Log In</a></small>
    </div>
{% endblock content %}

templates/users/profile.html
{% extends '../shop/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class='container'>
        <h3>{{user.username}}</h3>
    </div>
    <div class='container'>
        <img src="{{profile.profile_img.url}}" alt='profile picture'>
    </div>

{% endblock content %}

templates/users/registration.html
{% extends '../shop/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class='content-section'>
        <form method='POST'>
            {% csrf_token %}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Register Today</legend>
                {{form|crispy}}
            </fieldset>
            <div class='form-group'>
                <button class='btn btn-outline-info' type='submit'>Sign Up</button>
            </div>
        </form>
        <div class='border-top pt-3'>
            <small class='muted'>Already have an account? <a class='ml-2' href='{% url 'login' %}'>Login</a></small>
        </div>
    </div>
{% endblock content %}